### ISSUE TITLE
importing ocean issue + shader graph material

### ISSUE THREAD

**Issue by ivanmotta** [bearworks/URPSeaCloudFog#1]
When importing in 2021.3.4f1 the ocean shaders have lots of errors, and can't find a way to use the fog color inside a shader graph. Could you please clarify how to use it?
The xclouds and fog work beautifully, just can't integrate to other materials

**Comment by bearworks** [comment]
Shader Graph is not currently supported, Thank you for your feedback.

I will test it with unity2021

[image: image.png]


Ivan Motta ***@***.***> 于2022年9月21日周三 23:38写道：

**Comment by bearworks** [comment]
![image](https://user-images.githubusercontent.com/7309937/232334337-133c133b-1302-485d-8296-ce7bfac6eac9.png)

![image](https://user-images.githubusercontent.com/7309937/232334394-4940152a-0f2a-4eb4-a327-2aceb11a89d0.png)

now supports for shadergraph (with a subnode and an unlit shadergraph ) and unity 2021.3 

@ivanmotta
